"""Unique hotels data

Revision ID: 44447fdaf7cb
Revises: 40506467b729
Create Date: 2025-09-03 12:19:14.731337

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "44447fdaf7cb"
down_revision: str | None = "40506467b729"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("uq_hotel_title_location", "hotels", ["title", "location"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_hotel_title_location", "hotels", type_="unique")
    # ### end Alembic commands ###
