"""Unique data

Revision ID: 55d8bc1c9cc3
Revises: 44447fdaf7cb
Create Date: 2025-09-03 14:48:19.448653

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "55d8bc1c9cc3"
down_revision: str | None = "44447fdaf7cb"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "facilities", ["title"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "facilities", type_="unique")
    # ### end Alembic commands ###
